#!/bin/bash

path="$(cd "$(dirname "$0")"; pwd)"
opts="s|PATH|$dot|g"

echo "Creating a database tpch, the necessary tables and importing the data"
echo "This will take a few minutes, please wait"

sed -i $opts tpch_to_postgresql.sql

# remove the last pipe
for file in "$path"/*.tbl; do
  sed -i 's/|$//' "$file"
done

psql -U ${1?The script should be executed as follows: ./import_TPCH_to_postgresql.sh <DB_Username>}  -f tpch_to_postgresql.sql

echo "Reaching end of Script. Please visit the ./queries folder for sample queries generated by TPC-H to benchmark your database."
echo "A sample PostgreSQL script exists on Github WandersonSoares00/tpch. You may use it as an example to adapt your sample queries generated by TPCH."
echo "Do compare your output results with the expected output present in TPC-H documentation."

